### ISSUE TITLE
Need to `mkdir output` on fresh clone

### ISSUE THREAD

**Issue by verdverm** [cpard/scuel#1]
```
$ cue cmd tpch_gen
task failed: open output/tpch_q22.sql: no such file or directory

$ mkdir output
$ cue cmd tpch_gen
```

You could add a `mkdir` as a task before the file writes to fix this

**Comment by cpard** [comment]
hey @verdverm there seems to be an issue with mkdir before the writes. If I understand correctly, tasks are run concurrently which has the side effect of having writes that fail as they run before the mkdir happens.

Is there a way to force the tasks to run sequentially? I have the impression that if one task has a reference to another then they run sequentially but check the following code:

```
import "tool/file"

command: "tpch_gen": {

	 for i, R in rendered {
		// make a unique name when comprehending
		task: output: file.Mkdir & {
			path: "output/"
		}
		task: "write-\(i+1)": file.Create & {
			filename: "\(task.output.path)tpch_q\(i+1).sql"
			contents: R.content
		}
	}
}
```
The above results to the creation of the directory and some of the files to be written but not all of them, with a "no such file or directory" error. 

Shouldn't the reference to task.output.path inside the write task force the tasks to be executed sequentially?

**Comment by verdverm** [comment]
You can make an explicit dependency by adding an incomplete value to the before task and a reference to it in the after task(s). Referencing a concrete value will not create a dependency, and the referenced value doesn't need to ever be filled. If there is a field that will be filled, it serves both purposes.

Creating sequential tasks from a list is possible, by using the above method, but can run into performance issues (https://github.com/cue-lang/cue/issues/1795)

```cue
import "tool/file"

command: "tpch_gen": {
	// ensure our directory exists
	output: file.Mkdir & {
		path: "output/"
		done: _
	}

	for i, R in rendered {
		// make a unique name when comprehending
		"write-\(i+1)": file.Create & {
			$after: [output.done]
			filename: "\(output.path)tpch_q\(i+1).sql"
			contents: R.content
		}
	}
}

```

**Comment by cpard** [comment]
hey @verdverm thank you so much for the amazing support on this!

 I actually figured it out with the help of this https://cuetorials.com/patterns/scripts-and-tasks/ so thank you for the great effort you put on creating good documentation for CUElang, it's much needed.

The code is updated now and it should work without issues.
