### ISSUE TITLE
a few indentation outliers

### ISSUE THREAD

**Issue by verdverm** [cpard/scuel#2]
I noticed that `q1` and `q22` have different indentation patterns that the others

thoughts on tabs versus spaces?  (mine is typically tabs so the user can decide width / indentation scale)

You can use `unexpand -t4` on linux for the other files which use 4 spaces

**Comment by cpard** [comment]
yep, these two query templates were formatted differently. I made some changes and now q1 and q22 should be formatted correctly. Thanks for pointing this out!
